### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nmro97** [O11iee/TTAutoRecord#3]
hi ill start the exe it start working, after like 5 min i get the error , than the program does not get any new streams 
![Unbenannt](https://github.com/O11iee/TTAutoRecord/assets/149392722/e56ac641-2df6-4e3e-b8c6-1060d2507e92)

**Comment by O11iee** [comment]
Hi, that's odd. Make sure the executable is whitelisted on your AV and Firewall. Also check to see if the lives load in Firefox when you get the error.

**Comment by nmro97** [comment]
idk but the older version works better but sometimes he stops working to so ineed to restart the exe

**Comment by O11iee** [comment]
I am working on V4 right now which will be more stable

**Comment by nmro97** [comment]
so i whitelisted and the lives load on firefox normally but still got the error

**Comment by nmro97** [comment]
is there a way auto refresh without closing the exe ?

**Comment by nmro97** [comment]
keep geting an error after 15 mins of normally working like some sort of chrome error can u help , it would just work perfectly if i wouldnt get the error

**Comment by O11iee** [comment]
I have identified the issue and will release an early version of V4 this weekend

**Comment by nmro97** [comment]
thank you i also had the problem that the new version wasnt recording lives from some countries however the older version was recording them thats why i used the older version , idk why maybe cuz of the flv link but im not sure

**Comment by O11iee** [comment]
Yes its to do with the FLV link if their M3u8 doesn't work. I will change it to prioritise Ultra HD and fall back to a lower quality if the Ultra HD link doesn't exist

**Comment by nmro97** [comment]
thank you brother. waiting for de update

**Comment by nmro97** [comment]
hi bro i dont wanna border you but is there any updates ?

**Comment by O11iee** [comment]
> hi bro i dont wanna border you but is there any updates ?

Hi, sorry for the delay, keep running into unexpected hurdles and a lack of time to fix them. I will post what I have so far for you to use over the weekend, it's not perfect but its an improvement. I would keep checking it when you can to make sure it's still running. Debugging is enabled.

The prompt for admin permissions is to disable quick edit mode on the console window.

[https://github.com/O11iee/TTAutoRecord/releases/tag/v4.0.0-alpha](url)

**Comment by nmro97** [comment]
hi bro its working but it randomly started recording suggested lives like random 7 streams

**Comment by nmro97** [comment]
it started doing that like when nobody was live i follow _

**Comment by nmro97** [comment]
yes its doing it i just restarted it so noone was live i follow he started recording like 10 random streams from suggested

**Comment by O11iee** [comment]
What country are you connecting from?

**Comment by nmro97** [comment]
germany

**Comment by nmro97** [comment]
even if theres someone live i follow still recording 10 suggested lives now

**Comment by O11iee** [comment]
Make sure to change your tiktok language to English. It looks for the "Following" section which will fail if it's in a different language

**Comment by nmro97** [comment]
yea it was in english on browser but german on the app  does this change anything ?

**Comment by O11iee** [comment]
Potentially. Also be sure to get the cookies again after changing the language

**Comment by nmro97** [comment]
hi brotha its is still doing it if the following list is empty he gets the streams from suggested  both app and on broswer is in english

**Comment by nmro97** [comment]
hi so theres like another problem that like after 2 hours of stream the segments wont put together

**Comment by nmro97** [comment]
i had it on this night after i wake up i had no space he downloadet all tiktok on my pc haha xD

**Comment by nmro97** [comment]
so i used it for 2 days now i had only 2 problems using it first one is that if none of ur followers are live hell get suggested lives more than 10-20 streams,  the other problem is missing segments , otherwise it works perfect for me dit not stop working like the old version

**Comment by O11iee** [comment]
Hi, I have made sure it only gets the following now. I plan to ditch the whole auto concatenation as it's not reliable since it keeps changing resolution and bitrate. I will add a manual option in the GUI which will re-encode then concatenate. I'll add QuickSync and NVENC support to make it faster.

https://github.com/O11iee/TTAutoRecord/releases/tag/v4.0.0-alpha
