### ISSUE TITLE
ITS NOT not working since this morning

### ISSUE THREAD

**Issue by nmro97** [O11iee/TTAutoRecord#5]
hi after few debugs it gets the follower list but it says ;  all retries failed for url and then the streamers url  adjust your settings ! 
![Unbenannt](https://github.com/O11iee/TTAutoRecord/assets/149392722/a2a6b3aa-61c3-4acd-b23d-0bc464a24b20)

**Comment by O11iee** [comment]
> hi after few debugs it gets the follower list but it says ; all retries failed for url and then the streamers url adjust your settings ! ![Unbenannt](https://private-user-images.githubusercontent.com/149392722/290797883-a2a6b3aa-61c3-4acd-b23d-0bc464a24b20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Mzk1MDIsIm5iZiI6MTcwMjYzOTIwMiwicGF0aCI6Ii8xNDkzOTI3MjIvMjkwNzk3ODgzLWEyYTZiM2FhLTYxYzMtNGFjZC1iMjNkLTBiYzQ2NGEyNGIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxMTIwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmE5M2YyM2UyMDYzOTNjZGNjMDUyNTE2ZWVhNTVhODcwMWFmYjc2ZmI5ODI2MzFhZmM4ZTU4ZDI0ZmJkZTA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KYCUrWnInEZB8250lzn05wLc8TuBA9myf84-Hww549Y)

Hi, TikTok have restricted EU so that you need to login. Use US VPN as a temporary workaround.

**Comment by nmro97** [comment]
how long they will restrict do u know ?

**Comment by nmro97** [comment]
its working now u can close this

**Comment by O11iee** [comment]
Yes, TikTok reverted the changes as expected
